name: Azure Data Factory Deployment

on:
  push:
    branches:
      - main  # Adjust branch name as needed 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     - name: Install Azure CLI
        uses: docker://mcr.microsoft.com/azure-cli


      # Login to Azure
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Set Azure subscription
      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Validate ARM templates
      - name: Validate ARM templates
        run: |
          az deployment group validate --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file ./datafacsaireddydev/ARMTemplateForFactory.json --parameters ./datafacsaireddydev/ARMTemplateParametersForFactory.json

      # Deploy ARM templates
      - name: Deploy ARM templates
        run: |
          az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file ./datafacsaireddydev/ARMTemplateForFactory.json --parameters ./datafacsaireddydev/ARMTemplateParametersForFactory.json

      # Test Deployment
      

      # Logout from Azure
      - name: Logout from Azure
        run: az logout
