name: Azure Data Factory Deployment

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: self-hosted  # Assuming you have a self-hosted runner configured

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: azure/cli@v1  # Use the official Azure CLI action
        with:
          azure-cli-version: '2.30.0'  # Specify version to avoid breaking changes

      - name: Validate ARM templates
        run: |
          az deployment group validate --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file ./datafacsaireddydev/ARMTemplateForFactory.json --parameters ./datafacsaireddydev/ARMTemplateParametersForFactory.json

      - name: Deploy ARM templates
        run: |
          az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file ./datafacsaireddydev/ARMTemplateForFactory.json --parameters ./datafacsaireddydev/ARMTemplateParametersForFactory.json

      - name: Test Deployment
        run: |
          # Add testing steps here

      - name: Logout from Azure
        run: az logout
